jobs:
  include:
  - dist: xenial
    os: linux
  - dist: bionic
    os: linux
  - os: osx
os: linux
dist: xenial
language: c
compiler: gcc

before_install:
  # Set global flag
  - export TESTS="True"

  # Install R
  - if [[ $TRAVIS_OS_NAME == linux ]]; then
      sudo apt-get install r-base;
      export R_INSTALL_DIR=/usr/lib64/R
      export LD_LIBRARY_PATH=${R_INSTALL_DIR}:${LD_LIBRARY_PATH};
    elif [[ $TRAVIS_OS_NAME == osx ]]; then
      export HOMEBREW_AUTO_UPDATING=0;
      brew install --build-from-source r;
      export R_INSTALL_DIR=/usr/local/Cellar/R
      export DYLD_LIBRARY_PATH=${R_INSTALL_DIR}:${LD_LIBRARY_PATH};
    fi
  
  # Install q and set QHOME
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      QLIBDIR=l64; OD=$L64;
    elif [[ $TRAVIS_OS_NAME == "osx" ]]; then
      QLIBDIR=m64; OD=$M64;
    elif [[ $TRAVIS_OS_NAME == "windows" ]]; then
      QLIBDIR=w64; OD=$W64;
    else
      echo "unknown OS ('$TRAVIS_OS_NAME')" >&2; exit 1;
    fi
  - export QLIBDIR
  - mkdir qhome;
  - export QHOME=$(pwd)/qhome;
  - export PATH=$QHOME/$QLIBDIR:$PATH;
  
  # Set up q for testing and execute tests on multiple 
  - if [[ $TESTS == "True" && "x$OD" != "x" && "x$QLIC_KC" != "x" ]]; then
      export PATH=$R_INSTALL_DIR/lib:$PATH;
      curl -o ${QHOME}/q.zip -L $OD;
      unzip -d ${QHOME} ${QHOME}/q.zip;
      rm ${QHOME}/q.zip;
      echo -n $QLIC_KC |base64 --decode > ${QHOME}/kc.lic;
    else
      echo "No kdb+, no tests";
    fi

  # Set package name
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
      export FILE_TAIL="zip";
    else
      export FILE_TAIL="tgz";
    fi
  - export FILE_NAME=$FILE_ROOT-$TRAVIS_OS_NAME-$ARCH-$TRAVIS_BRANCH.$FILE_TAIL

  # Build package
  - mkdir build
  - cd build
  - if [[ $TRAVIS_OS_NAME == windows ]]; then
      cmake --config Release ..;
      cmake --config Release --build . --target install;
    else
      cmake ..;
      cmake --build . --target install;
    fi
  - cd ..

script:
  - if [[ $TESTS == "True" && "x$OD" != "x" && "x$QLIC_KC" != "x" ]]; then
      q tests/test.q;
    fi
  - if [[ $TRAVIS_OS_NAME == "windows" && $BUILD == "True" ]]; then
      7z a -tzip -r $FILE_NAME ./build/$FILE_ROOT/*;
    elif [[ $BUILD == "True" && ( $TRAVIS_OS_NAME == "linux" || $TRAVIS_OS_NAME == "osx" ) ]]; then  
      tar  -zcvf $FILE_NAME -C build/$FILE_ROOT .;
    elif [[ $TRAVIS_OS_NAME == "windows" ]]; then
      7z a -tzip $FILE_NAME README.md install.bat install32.bat LICENSE q examples;
    elif [[ $TRAVIS_OS_NAME == "linux" || $TRAVIS_OS_NAME == "osx" ]]; then
      tar  -zcvf $FILE_NAME README.md install.sh LICENSE q examples;
    fi

deploy:
  provider: releases
  api_key:
    secure: KFMpWB7nPE4j9pkCPnuZH6tHIFGDWjk/Vv4nHTZdqFVKjCcjlS58GyKmMHtLNG4AZF8rbfhMKGINh4Xu47aOonrGhcwi2rUu06tmmGX06msnmRzqWqCqouJN3rORJgd9dOQLrOPxullBkhfFpzDj0XX5eVqGyJEKj1GK8IAKiuaIeGSVFd+P3BTBLELxnhxJZ5xOoeyWvyX9KXIj+/ZYy21kYO8SaNpSSx4LNvJHjudzCmd+iG6ReDA8DBuTd5Mr4yno+E6JvQVcGBkphQjIvvGEgUnSCVJAxvwdhAkbH7ANyawPqb+zNCT+P0MzMcHccMnzkh6/Y7T2o1qkgsLQbI/Du0UwzZDm3UVuF+T1NwG/DIMJhW2e99L1z9uQiGOce0nd+KjG92Vh6UHosK6zdiJmyPl6YY4NViKQrAurvUi2xrd6JpK7rvnQPezs7xxiCqfjS0l0G2afzLU+PdFM08M4DfhPQD7E5wyrHy3BxhtaTKTq4rMSfiPtBMoCApOlmcsU+UP73E+kQHE7+DrI4kkgN+DGgZEQotK/zwC6UtT+AtTU2N+Qn3OJQytVMERPARuospNXuq8LM8sLQ/EgnD1DtwNafJnLVLTrU+doT2esdxW67mytJw0r0pRhjF34K7Oc1KSpBgqPzeZMQv2ET4+4c1p8v7Sdz0Hi2a2g8RE=
  file_glob: true
  file: embedr_*.tar.gz
  skip_cleanup: true
  on:
    tags: true
