language: c
os:
- linux
- osx
before_install:
- if [ $TRAVIS_OS_NAME = linux ]; then
    sudo apt-get install r-base;
  fi
- if [ $TRAVIS_OS_NAME = osx ]; then
    export HOMEBREW_AUTO_UPDATING=0;
    brew install --build-from-source r;
  fi
script:
- make
- echo "Preparing version $TRAVIS_BRANCH-$TRAVIS_COMMIT"
- mkdir embedr; cp -r rinit.q rtest.q l32 l64 m32 m64 embedr/ || true;
- echo "$TRAVIS_BRANCH-$TRAVIS_COMMIT" > embedr/VERSION.embedr;
- cp LICENSE embedr/LICENSE.embedr; cp README.md embedr/README.embedr;
- tar czvf embedr_$TRAVIS_OS_NAME-$TRAVIS_BRANCH.tar.gz embedr
- echo "Packaged as embedr_$TRAVIS_OS_NAME-$TRAVIS_BRANCH.tar.gz"
deploy:
  provider: releases
  token: "$GITHUB_APIKEY"
  file_glob: true
  file: embedr_*.tar.gz
  skip_cleanup: true
  on:
    tags: true