image: Visual Studio 2017
# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

environment:
  global:
    GCC_PATH: mingw_64
  matrix:
  - BITS: 64
    R_ARCH: x64

  - BITS: 32
    R_ARCH: i386

build_script:
- cmd: mkdir w%BITS%
- cmd: R.exe CMD SHLIB -o w%BITS%/embedr.dll src/embedr.c src/w%BITS%/q.a -lws2_32

after_build:
- cmd: mkdir embedr
- ps: Copy-Item w$env:BITS -Destination .\embedr\w$env:BITS -Recurse
- ps: Copy-Item rinit.q -Destination .\embedr
- ps: Copy-Item rtest.q -Destination .\embedr
- ps: Copy-Item LICENSE -Destination .\embedr\LICENSE.embedr
- ps: Copy-Item README.md -Destination .\embedr\README.embedr
- IF /I "%APPVEYOR_REPO_TAG%" == "false" set APPVEYOR_REPO_TAG_NAME=%APPVEYOR_REPO_BRANCH%
- cmd: 7z a embedr_win%BITS%-%APPVEYOR_REPO_TAG_NAME%.zip %APPVEYOR_BUILD_FOLDER%\embedr
artifacts:
- path: 'embedr_win*.zip'

deploy:
  provider: GitHub
  draft: true
  auth_token:
    secure: P2U9jL8L7es2Iv/SSthmQ+a9qSZ41OSiGHjSdOMve7eKwWoo3zh/8DvJqkkMfhS7
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
